version: '3.8'
services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - '${API_PORT}:3000'
      - '5555:5555'
    depends_on:
      - postgres-dev
    env_file:
      - ../.env
    command: sh -c 'while ! nc -z ${POSTGRES_HOST} ${POSTGRES_PORT}; do sleep 1; done; npm run migrate:dev && npm run prisma:seed && npm run prisma:studio & npm run start:prod'
    networks:
      - malac-prodavac

  postgres-dev:
    image: postgis/postgis:15-3.4
    container_name: postgres-dev
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - ../.env
    volumes:
      - malac-prodavac-postgres-dev:/var/lib/postgresql/data
    networks:
      - malac-prodavac

volumes:
  malac-prodavac-postgres-dev:
    name: malac-prodavac-postgres-dev

networks:
  malac-prodavac:
