version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - ../.env
    volumes:
      - malac-prodavac-postgres:/var/lib/postgresql/data

volumes:
  malac-prodavac-postgres:
    name: malac-prodavac-postgres
