version: '3.8'
services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - '${API_PORT:-3000}:3000'
    depends_on:
      - postgres
    env_file:
      - ../.env
    command: sh -c 'while ! nc -z ${POSTGRES_HOST:-postgres} ${POSTGRES_PORT:-5432}; do sleep 1; done; npm run migrate:dev && npm run start:prod'
    networks:
      - malac-prodavac

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - ../.env
    volumes:
      - malac-prodavac-postgres:/var/lib/postgresql/data
    networks:
      - malac-prodavac

volumes:
  malac-prodavac-postgres:
    name: malac-prodavac-postgres

networks:
  malac-prodavac:
