version: '3.8'
services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - '${API_PORT:-3000}:3000'
      - '5555:5555'
    depends_on:
      - postgres-stage
    env_file:
      - ../.env
    command: sh -c 'while ! nc -z ${POSTGRES_HOST:-postgres-stage} ${POSTGRES_PORT:-5432}; do sleep 1; done; npm run migrate:deploy && npm run prisma:seed && npm run prisma:studio & npm run start:prod'
    networks:
      - malac-prodavac

  postgres-stage:
    image: postgis/postgis:15-3.4
    container_name: postgres-stage
    restart: always
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - ../.env
    volumes:
      - malac-prodavac-postgres-stage:/var/lib/postgresql/data
    networks:
      - malac-prodavac

volumes:
  malac-prodavac-postgres-stage:
    name: malac-prodavac-postgres-stage

networks:
  malac-prodavac:
